### ISSUE TITLE
Build fails with gcc 10.2.1 on CentOS

### ISSUE THREAD

**Issue by reverendbedford** [libMesh/libmesh#3329]
The relatively recent `mesh/poly2tri_triangulator` does not compile on CentOS with gcc 10.2.1.  The compile error is

```
./include/libmesh/poly2tri_triangulator.h:139:31: error: 'unique_ptr' is not a member of 'std'
  139 |   std::map<const Hole *, std::unique_ptr<ArbitraryHole>> replaced_holes;
      |                               ^~~~~~~~~~
./include/libmesh/poly2tri_triangulator.h:31:1: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
...
```

The fix is just to `#include <memory>` in the header.  I'll upload a PR in a minute.

**Comment by roystgnr** [comment]
Thanks for catching this!
