### PR TITLE
 Enable base-side in InfFE::reinit(elem, side) 

### PR DESCRIPTION
**Pull request by BalticPinguin**
The main issue I try to address is that I want to compute properties of the infinite elements at the boundary to the FEM-region. Thus, I need `side==base_side` in `InfFE::reinit(elem, side)`.

Along the lines, I'd like to fix some errors I introduced in #1981 (sorry for that).
and to make the above-mentioned function working, the `InfFE::inverse_map()` must give points outside the element when I feed it with points not being in the element.

The changes are actually more since I ran the `reindent.sh`-script on the code...

I hope not to introduce some strange or wrong behaviour; my tests were all successfull.

### CODE REVIEW

**Comment by roystgnr** [comment]
The failed test died with a bunch of -Werror -Wshadow results:

```
../src/fe/inf_fe_boundary.C: In member function ‘void libMesh::InfFE<Dim, T_radial, T_map>::init_face_shape_functions(const std::vector<libMesh::Point>&, const libMesh::Elem*)’:
../src/fe/inf_fe_boundary.C:292:42: error: declaration of ‘dpsideta_map’ shadows a previous local [-Werror=shadow]
         std::vector<std::vector<Real>> & dpsideta_map = this->_fe_map->get_dpsideta();
                                          ^~~~~~~~~~~~
../src/fe/inf_fe_boundary.C:272:38: note: shadowed declaration is here
     std::vector<std::vector<Real>> & dpsideta_map = this->_fe_map->get_dpsideta();
                                      ^~~~~~~~~~~~
../src/fe/inf_fe_boundary.C:296:42: error: declaration of ‘d2psidxideta_map’ shadows a previous local [-Werror=shadow]
         std::vector<std::vector<Real>> & d2psidxideta_map = this->_fe_map->get_d2psidxideta();
                                          ^~~~~~~~~~~~~~~~
../src/fe/inf_fe_boundary.C:275:38: note: shadowed declaration is here
     std::vector<std::vector<Real>> & d2psidxideta_map = this->_fe_map->get_d2psidxideta();
                                      ^~~~~~~~~~~~~~~~
../src/fe/inf_fe_boundary.C:297:42: error: declaration of ‘d2psideta2_map’ shadows a previous local [-Werror=shadow]
         std::vector<std::vector<Real>> & d2psideta2_map = this->_fe_map->get_d2psideta2();
                                          ^~~~~~~~~~~~~~
../src/fe/inf_fe_boundary.C:276:38: note: shadowed declaration is here
     std::vector<std::vector<Real>> & d2psideta2_map = this->_fe_map->get_d2psideta2();
                                      ^~~~~~~~~~~~~~
```

**Comment by roystgnr** [comment]
I don't *see* any problems, but I don't use infinite elements so it's certainly possible I'm missing something.  We can merge this as-is, but even if it's working for you now I can easily imagine breaking it in the future.  Could you add a unit test, or maybe a QoI in one of the infinite element examples, which would cover the new code?

**Comment by BalticPinguin** [comment]
yes, I'll prepare one. Should I add it to this PR?
I hope, within next week it is ready.

**Comment by roystgnr** [comment]
> Should I add it to this PR?

Up to you and @jwpeterson:  IMHO this looks like it's worth getting into 1.4.0, which he's starting to prepare, so if he's in a hurry and the unit test might take some time then we can merge now.

**Comment by jwpeterson** [comment]
> which he's starting to prepare

I've started thinking about it, but haven't done anything yet. I'm fine with whatever order we: 
* merge this
* start the v1.4.0 branch
* merge a unit test for this

since it should be no problem to cherry-pick the commits.

**Comment by roystgnr** [comment]
If the test is taking a while I'll merge now; missing coverage for a new feature isn't good but it's not a likely source regression for existing codes either.
