### ISSUE TITLE
Libmesh fails to compile on OSX with gcc-4.10.0 

### ISSUE THREAD

**Issue by NAThompson** [libMesh/libmesh#322]
Looks like this issue has been [seen before](http://sourceforge.net/p/libmesh/mailman/message/31665383/), though it arose with gcc-4.8. For reference, the error message is

```
CXX      src/mesh/libmesh_dbg_la-exodusII_io_helper.lo
In file included from /usr/local/include/c++/4.10.0/cstring:42:0,
             from ./include/libmesh/dense_matrix.h:30,
             from ./include/libmesh/diff_context.h:24,
             from ./include/libmesh/fem_context.h:24,
             from ./include/libmesh/fem_function_base.h:31,
             from ./include/libmesh/system.h:31,
             from ../src/mesh/exodusII_io_helper.C:31:
/usr/include/string.h:145:1: error: 'errno_t' does not name a type
 errno_t memset_s(void *, rsize_t, int, rsize_t) __OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_7_0);
```

It [seems](http://stackoverflow.com/questions/1464711/how-to-detect-if-errno-t-is-defined) that `errno_t` is superfluous, and should be replaced by `int` in `string.h`, but that made the problem worse. So there is no easy fix to gcc. 

I'm going to make John's workaround stated in the link above permanent, namely change

```
  // Just doing this ifdef to be completely safe                                         
#ifndef LIBMESH_USE_COMPLEX_NUMBERS
 if(_val.size())
     std::memset(&_val[0], 0, sizeof(T) * _val.size()); 
#else
    std::fill (_val.begin(), _val.end(), 0.);
#endif
```

to 

```
std::fill (_val.begin(), _val.end(),  static_cast<T>(0));
```

Unfortunately this alone won't allow compilation, as it exposed a more [horrifying](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61387) issue with g++-4.10, but one thing at a time.
