### ISSUE TITLE
Netcdf build error with Intel-14

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#602]
Just leaving this here so I don't lose track of it.  This version of the Intel compiler is supposed to work with GCC 4.8.0.

```
  CC       jdata.o
  CC       nc_iter.o
  CC       ConvertUTF.o
ncgentab.c(1328): error: expected a ";"
    _Pragma ("GCC diagnostic push") _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"") _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
                                    ^

ncgentab.c(1331): error: expected a ";"
  }
  ^

ncgentab.c(1546): error: expected a ";"
    _Pragma ("GCC diagnostic push") _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"") _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
                                    ^

ncgentab.c(1550): error: expected a ";"
    goto yynewstate;
    ^

ncgentab.c(2790): error: expected a ";"
    _Pragma ("GCC diagnostic push") _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"") _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
                                    ^

ncgentab.c(2796): error: expected a ";"
    do { if (ncgdebug) { fprintf (stderr, "%s ", "Shifting"); yy_symbol_print (stderr, yystos[yyn], yyvsp); fprintf (stderr, "\n"); } } while (0);
    ^

compilation aborted for /home/moosetest/.ccache/tmp/ncgentab.stdout.hpcbuild6.14469.SobNOI.i (code 2)

```

**Comment by jwpeterson** [comment]
I'm going to close this since I don't have a machine handy where it manifests currently.  It also sounds like more of a netcdf issue than a libmesh issue.

**Comment by jwpeterson** [comment]
This issue persists in Intel 15.

```
ncgentab.c(1328): error: expected a ";"
    _Pragma ("GCC diagnostic push") _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"") _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
                                    ^

ncgentab.c(1331): error: expected a ";"
  }
  ^

ncgentab.c(1546): error: expected a ";"
    _Pragma ("GCC diagnostic push") _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"") _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
                                    ^

ncgentab.c(1550): error: expected a ";"
    goto yynewstate;
    ^

ncgentab.c(2790): error: expected a ";"
    _Pragma ("GCC diagnostic push") _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"") _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
                                    ^

ncgentab.c(2796): error: expected a ";"
    do { if (ncgdebug) { fprintf (stderr, "%s ", "Shifting"); yy_symbol_print (stderr, yystos[yyn], yyvsp); fprintf (stderr, "\n"); } } while (0);
    ^
```

**Comment by jwpeterson** [comment]
Going to assume this is fixed either by the newer version of NetCDF in #1326 or simply by using newer compilers...
