### ISSUE TITLE
Guessed include guards for messing with PETSc internals were wrong 

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#516]
I guessed that the new code in `PetscMatrix::update_preallocation_and_zero()` would work for PETSc 3.3.0 and newer, but it doesn't work with 3.4.3:

```
petsc_matrix.C:430:13: error: 'struct _p_Mat' has no member named 'nonzerostate'
```

I will have to bump the version used in the guards here and the associated example.

**Comment by jwpeterson** [comment]
`Mat::nonzerostate` seems to have been added in petsc/petsc@e56f5c9e.  The first release it made it into was 3.5.0.
