### ISSUE TITLE
Installation: 6 warnings and 1 error generated

### ISSUE THREAD

**Issue by agiordan96** [libMesh/libmesh#3767]
Hello all, 

while installing libMesh, I have been facing with the following (see attached config.log file) 6 warnings and 1 error 

(../LIBMESH/src/solvers/petsc_linear_solver.C:1570:10: error: duplicate case value: 'KSP_CONVERGED_CG_CONSTRAINED' and 'KSP_CONVERGED_STEP_LENGTH' both equal '6'
    case KSP_CONVERGED_STEP_LENGTH     : return CONVERGED_STEP_LENGTH;)
    
Anyone knows how to solve this? 

Thanks!:)

**Comment by jwpeterson** [comment]
This is likely due to using too new a version of PETSc (3.20.3 was tagged Dec 30 2023). If it's not essential for you to use that version, then you can likely fix the problem by using a 3.19.x PETSc...

**Comment by agiordan96** [comment]
Thanks for your quick reply!

It is unfortunately necessary... I could use 3.20.2, but I dont know if it fixes the issue. Are you by any chance aware of how long it will take to make libMesh compatible with the new version of petsc?

**Comment by lindsayad** [comment]
I am on PETSc `main`, commit `e4cb84850f3`, and I have no problem building libMesh

**Comment by jwpeterson** [comment]
It's hard to say, you can likely fix the `duplicate case value` error simply by commenting out the duplicate. Fixing the petscdmlibmeshimpl.C code is trickier because it uses "private" struct members like `_p_PetscObject` directly. Luckily it's not really used by anything, so you may have some luck just commenting out lines there as well.

**Comment by lindsayad** [comment]
What libMesh hash are you using? Line 770 of petscdmlibmeshimpl.C in current libMesh `devel` is not the line you pasted, and the last time that file was modified was on August 8th, so it seems that you're losing a libMesh that is at least a few months old

**Comment by jwpeterson** [comment]
> you're losing a libMesh that is at least a few months old

Oops, guess I should have asked that question first!

**Comment by agiordan96** [comment]
And I guess I should have checked what version I was downloading. I used 1.6.2, as in the IBAMR instructions I am reading that was (literally called) the latest. 
Will try with newer version and let you know tomorrow at the latest, thank you all for helping this quickly!

**Comment by agiordan96** [comment]
Unfortunately, the error persists with libMesh version 1.7.1....

``../LIBMESH/src/solvers/petscdmlibmeshimpl.C:822:120: error: no member named 'type' in '_p_PetscObject'
    LIBMESH_SETERRQ2(((PetscObject)dm)->comm, PETSC_ERR_ARG_WRONG, "DM of type %s, not of type %s", ((PetscObject)dm)->type, DMLIBMESH);

../LIBMESH/src/solvers/petscdmlibmeshimpl.C:904:120: error: no member named 'type' in '_p_PetscObject'
    LIBMESH_SETERRQ2(((PetscObject)dm)->comm, PETSC_ERR_ARG_WRONG, "DM of type %s, not of type %s", ((PetscObject)dm)->type, DMLIBMESH);


../LIBMESH/src/solvers/petscdmlibmeshimpl.C:904:120: error: no member named 'type' in '_p_PetscObject'
    LIBMESH_SETERRQ2(((PetscObject)dm)->comm, PETSC_ERR_ARG_WRONG, "DM of type %s, not of type %s", ((PetscObject)dm)->type, DMLIBMESH);

Any ideas, other than downgrading petsc to 3.20.2?

**Comment by jwpeterson** [comment]
> Any ideas, other than downgrading petsc to 3.20.2?

Yes, you need to use libmesh master if you want to use that new of a PETSc. The 1.7.1 release it itself also quite old.

**Comment by agiordan96** [comment]
Meaning the master would work with 3.20.3 or 3.20.2?

**Comment by jwpeterson** [comment]
Yes, according to @lindsayad's (https://github.com/libMesh/libmesh/issues/3767#issuecomment-1894122158) that will work.

**Comment by lindsayad** [comment]
I will not guarantee that it will work as using PETSc main results in a version that is effectively infinite so it will have different comparison results in macros, but it is certainly more likely to work. If it works with PETSc main but not with the 3.20.3 release, then I would definitely submit fixes to support you
