### ISSUE TITLE
Libmesh no longer compiles with GCC 4.8?

### ISSUE THREAD

**Issue by jwpeterson** [libMesh/libmesh#1490]
Failure log is [here](https://www.moosebuild.org/job/131573/).

I'm confused because the error message
```
../src/mesh/mesh_tools.C: In function ‘void libMesh::MeshTools::find_boundary_nodes(const libMesh::MeshBase&, std::vector<bool>&)’:
../src/mesh/mesh_tools.C:305:68: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = const libMesh::Elem; _Dp = std::default_delete<const libMesh::Elem>]’
           const UniquePtr<const Elem> side = elem->build_side_ptr(s);
                                                                    ^
In file included from /opt/min_moose/gcc-4.8.4/include/c++/4.8.4/memory:81:0,
                 from ./include/libmesh/auto_ptr.h:42,
                 from ./include/libmesh/parallel.h:25,
                 from ./include/libmesh/libmesh.h:28,
                 from ./include/libmesh/bounding_box.h:24,
                 from ./include/libmesh/elem.h:25,
                 from ../src/mesh/mesh_tools.C:21:
/opt/min_moose/gcc-4.8.4/include/c++/4.8.4/bits/unique_ptr.h:273:7: error: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^
```
is on a line of code that I don't *think* has changed much recently, and it works fine with newer compilers. This compiler also claims to support `std::unique_ptr` according to configure:
```
checking for C++11 std::unique_ptr support... yes
```
so it shouldn't be an issue with a non-standard boost::unique_ptr or something along those lines.

**Comment by roystgnr** [comment]
That definitely looked like a compiler bug to me, but I'm glad the workaround wasn't much hassle.  Did that close out the issue?
